spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mydatabase
#    url: jdbc:postgresql://postgres:5432/mydatabase
    username: myuser
    password: "secret"
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.yandex.ru
    protocol: smtp
    username: ${MAIL_USER}
    password: ${MAIL_PASSWORD}
    port: 587
